#Tomcat
server:
  port: 8081
  servlet:
    context-path: /gaomao

# DataSource todo 读写分离
spring:
  ## 数据源配置
  datasource:
    username: root
    password: l8o8g8o8
    url: jdbc:mysql://127.0.0.1:3306/gaomao?characterEncoding=utf8&serverTimeZone=Shanghai
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: gaomao-datasource
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        jdbc:
          time_zone: Asia/Shanghai
        hbm2ddl:
          auto: validate
  ## Redis配置
  redis:
    host: localhost
    port: 6379
    jedis:
      pool:
        max-wait: 30000
        max-active: 100
        max-idle: 20
        min-idle: 0
    timeout: 3000
  jackson:
    serialization:
      fail-on-empty-beans: false
# 日志级别配置
logging:
  level:
    root: info
    com.cyou: debug
gaomao:
  developers:
    - 方小白
    - 巧克力
  url:
    notfilter:
      urls:
        - "/login**"
        - "/app/getVerificationCode"
        - "/app/login"
        - "/doLogin**"
        - "/favicon.ico"
  jwt:
    expiration: 6000
    secret: gaomao
    token-header: authentication
# 系统自定义配置